#!/bin/bash

mkdir missing
./license-scanner.sh  java -n com.hedera.hashgraph:app -v 0.55.2 -m manual-additions.csv -N -e Apache-2.0 -e MIT -e BSD-3-Clause -e BSD-2-Clause -e EPL-2.0 -e EPL-1.0 -e MPL-2.0 -e CDDL-1.0 -e EDL-1.0 -e Unlicense -e ISC > missing/consensus-node.csv
./license-scanner.sh  java -n com.hedera.hashgraph:sdk -v 2.43.0 -m manual-additions.csv -N -e Apache-2.0 -e MIT -e BSD-3-Clause -e BSD-2-Clause -e EPL-2.0 -e EPL-1.0 -e MPL-2.0 -e CDDL-1.0 -e EDL-1.0 -e Unlicense -e ISC > missing/sdk-java.csv
./license-scanner.sh  java -n com.hedera.hashgraph:did-sdk-java -v 1.0.0 -m manual-additions.csv -N -e Apache-2.0 -e MIT -e BSD-3-Clause -e BSD-2-Clause -e EPL-2.0 -e EPL-1.0 -e MPL-2.0 -e CDDL-1.0 -e EDL-1.0 -e Unlicense -e ISC > missing/did-sdk-java.csv
./license-scanner.sh  java -r https://github.com/OpenElements/hedera-enterprise -m manual-additions.csv -N -e Apache-2.0 -e MIT -e BSD-3-Clause -e BSD-2-Clause -e EPL-2.0 -e EPL-1.0 -e MPL-2.0 -e CDDL-1.0 -e EDL-1.0 -e Unlicense -e ISC > missing/hedera-enterprise.csv
./license-scanner.sh  rust -r https://github.com/hashgraph/hedera-sdk-rust -m manual-additions.csv -N -e Apache-2.0 -e MIT -e BSD-3-Clause -e BSD-2-Clause -e EPL-2.0 -e EPL-1.0 -e MPL-2.0 -e CDDL-1.0 -e EDL-1.0 -e Unlicense -e ISC > missing/sdk-rust.csv
./license-scanner.sh  swift -r https://github.com/hashgraph/hedera-sdk-swift -m manual-additions.csv -N -e Apache-2.0 -e MIT -e BSD-3-Clause -e BSD-2-Clause -e EPL-2.0 -e EPL-1.0 -e MPL-2.0 -e CDDL-1.0 -e EDL-1.0 -e Unlicense -e ISC > missing/sdk-swift.csv
./license-scanner.sh  go -r https://github.com/hashgraph/hedera-sdk-go -m manual-additions.csv -N -e Apache-2.0 -e MIT -e BSD-3-Clause -e BSD-2-Clause -e EPL-2.0 -e EPL-1.0 -e MPL-2.0 -e CDDL-1.0 -e EDL-1.0 -e Unlicense -e ISC > missing/sdk-go.csv
./license-scanner.sh  js -r https://github.com/hashgraph/hedera-sdk-js -m manual-additions.csv -N -e Apache-2.0 -e MIT -e BSD-3-Clause -e BSD-2-Clause -e EPL-2.0 -e EPL-1.0 -e MPL-2.0 -e CDDL-1.0 -e EDL-1.0 -e Unlicense -e ISC > missing/sdk-js.csv
./license-scanner.sh  js -r https://github.com/hashgraph/solo -m manual-additions.csv -N -e Apache-2.0 -e MIT -e BSD-3-Clause -e BSD-2-Clause -e EPL-2.0 -e EPL-1.0 -e MPL-2.0 -e CDDL-1.0 -e EDL-1.0 -e Unlicense -e ISC > missing/solo.csv
./license-scanner.sh  js -r https://github.com/hashgraph/hedera-local-node -m manual-additions.csv -N -e Apache-2.0 -e MIT -e BSD-3-Clause -e BSD-2-Clause -e EPL-2.0 -e EPL-1.0 -e MPL-2.0 -e CDDL-1.0 -e EDL-1.0 -e Unlicense -e ISC > missing/local-node.csv
./license-scanner.sh  js -r https://github.com/hashgraph/hedera-mirror-node-explorer -m manual-additions.csv -N -e Apache-2.0 -e MIT -e BSD-3-Clause -e BSD-2-Clause -e EPL-2.0 -e EPL-1.0 -e MPL-2.0 -e CDDL-1.0 -e EDL-1.0 -e Unlicense -e ISC > missing/mirror-node-explorer.csv
./license-scanner.sh  js -r https://github.com/hashgraph/hedera-json-rpc-relay -m manual-additions.csv -N -e Apache-2.0 -e MIT -e BSD-3-Clause -e BSD-2-Clause -e EPL-2.0 -e EPL-1.0 -e MPL-2.0 -e CDDL-1.0 -e EDL-1.0 -e Unlicense -e ISC > missing/json-rpc-relay.csv
./license-scanner.sh  js -r https://github.com/gomintco/gomint-api -m manual-additions.csv -N -e Apache-2.0 -e MIT -e BSD-3-Clause -e BSD-2-Clause -e EPL-2.0 -e EPL-1.0 -e MPL-2.0 -e CDDL-1.0 -e EDL-1.0 -e Unlicense -e ISC > missing/gomint-api.csv
./license-scanner.sh  js -r https://github.com/gomintco/gomint-client -m manual-additions.csv -N -e Apache-2.0 -e MIT -e BSD-3-Clause -e BSD-2-Clause -e EPL-2.0 -e EPL-1.0 -e MPL-2.0 -e CDDL-1.0 -e EDL-1.0 -e Unlicense -e ISC > missing/gomint-client.csv
./license-scanner.sh  python -r https://github.com/wensheng/hedera-sdk-py -m manual-additions.csv -N -e Apache-2.0 -e MIT -e BSD-3-Clause -e BSD-2-Clause -e EPL-2.0 -e EPL-1.0 -e MPL-2.0 -e CDDL-1.0 -e EDL-1.0 -e Unlicense -e ISC > missing/sdk-python-1.csv
./license-scanner.sh  python -r https://github.com/nadineloepfe/hedera_sdk_python -m manual-additions.csv -N -e Apache-2.0 -e MIT -e BSD-3-Clause -e BSD-2-Clause -e EPL-2.0 -e EPL-1.0 -e MPL-2.0 -e CDDL-1.0 -e EDL-1.0 -e Unlicense -e ISC > missing/sdk-python-2.csv
