name: Testing the scanner action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: run scanner action
        id: scanner
        uses: hendrikebbers/license-scanner-action@main
        with:
          language: "java"

      - name: Display Licenses Content
        shell: bash
        run: |
          echo "Licenses Content: ${{ steps.scanner.outputs.licenses }}"
